version: '3'

services:
  db:
    image: postgres:16
    env_file:
      - .env.prod
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env.prod

volumes:
  db-data: