version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: unless-stopped
    env_file:
      - .env.prod
    command: gunicorn --bind 0.0.0.0:8000 SoloPizza.wsgi

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - redis
      - web
    restart: unless-stopped
    env_file:
      - .env.prod
    command: celery -A SoloPizza worker --loglevel=info

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - redis
      - web
    restart: unless-stopped
    env_file:
      - .env.prod
    command: celery -A SoloPizza beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=info

volumes:
  redis-data: