services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env.dev
    command: python manage.py runserver 0.0.0.0:8000

  celery_worker:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    env_file:
      - .env.dev
    command: celery -A SoloPizza worker --loglevel=info

  celery_beat:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    env_file:
      - .env.dev
    command: celery -A SoloPizza beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=info

volumes:
  redis-data:
